name: Hello GitHub Actions

on: push

jobs:

  hello:

    runs-on: ubuntu-latest

    steps:

      - name: Say Hello
        run: echo "Hello YouTube Shorts!!!"

      - name: Check out repo
        uses: actions/checkout@v6

      - name: List repo files
        run: ls -la
